version: "3"
services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3305:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
    - "8080:8080"

  employees:
    image: employees
    ports:
      - 5000:5000
    environment:
      - PRODUCTION="PRODUCTION"